### ISSUE TITLE
Textbox Group name property not accessible

### ISSUE THREAD

**Issue by SteveHawes** [Servoy/servoy-extra-components#10]
There is no getName() method available to get the name of the element. This means that to use the component in a controller.focusField() call the name must be coded as a string. If the name subsequently changes there is no way to easily identify the issue. If the getName() method was available then you could write:
```javascript
controller.focusField(elements.myField.getName(), true);
```
In this manner any change to the name of the field would immediately result in an error and build marker.

This method appears to be missing from all the servoy-extra, servoy-default and bootstrap components I have checked.

**Comment by jcompagner** [comment]
it does not have a getName api. But the question is why would you need this for this specific call
because focusField will not work on that textfield group because the textfield group has no requestFocus method (see #11 )

also this api call should not just be added, because getName() as an api call would mean a call to the client to get the value,  So as best it would have to be a model property

Or servoy itself has to always overlay getName() as a thing that you can call on all web components and return then the name property. But then this is a feature reques for servoy itself not this component.

**Comment by SteveHawes** [comment]
I have added a feature request to the support system for this. [SVY-10769](https://support.servoy.com/browse/SVY-10769)
