### ISSUE TITLE
Sidenav takes full width in form

### ISSUE THREAD

**Issue by servoyguru** [Servoy/servoy-extra-components#19]
In the 'github.com/Servoy/sample_crm’ that does a great demo of a responsive NG client solution, there is a ‘servoynavigation-menubar’ component that plays nicely in a column with tabless panel next to it.

But it looks like Servoy are pushing to use the ‘servoyextra-sidenav’ component instead, as that installs from the Web Package Manager, whereas the one above had to be installed from a zip package, so I assume is not supported properly. This sidenav component does not play nicely in a column if I do a direct replacement of the above menubar with a sidenav, it takes over the whole column width and will only work if I put two columns in row and set the styles with ‘col-xx-y’.

Can the sidenav be made more responsive or can you release the (side)menubar thru the Web Packages?? (Or how can I get sidenav to replace it and be responsive in one column??)
I have done this in the sampleCRM attached
[svySampleCrmSideNav.servoy.zip](https://github.com/Servoy/servoy-extra-components/files/914189/svySampleCrmSideNav.servoy.zip)

**Comment by paronne** [comment]
Hi, differently from the servoynavigation-menubar the sidenav menu comes with a generic style.
By default the menu does indeed take 100% of the available width. If you place into a column it will take the whole column size. You can control it's styling with your own CSS (for example setting a max-width of 250px) or with a different form layout structure (for example you place it within a div with fixed width). 

It does not have a built-in responsive behavior, but you can achieve it with CSS.

A simple example is:
<pre>
/* menu collapse showind only the icon when the screen size is smaller than 992px */
@media screen and (max-width: 992px) {
.svy-sidenav {
	max-width: 48px;
}

.svy-sidenav-item {
    width: 48px;
    overflow: hidden;
    height: 32px;
}

.svy-sidenav-divider {
    display: none;
}
}
</pre>

**Comment by servoyguru** [comment]
Hi Paolo, thanks for the comment, but it still does not work nicely in a responsive grid compared to the other component. I took the 'SideNav' example and put it in to a BS grid with SideNav in a column and a tab(less) panel in the column next to it. 
The 1st problem here is that the tab(less) panel does not expand to full height, even if I set a style for it of full height (as I do for sidenav) (e.g. for Customers). It grows a bit more if the SideNav is expanded (e.g. when Products is chosen), but it is not the same as the ‘servoynavigation-menubar’.
The 2nd problem is when putting it in to it's own column, when you toggle it to collapse, the right column doesn't 'expand' to fill up the space, unlike the ‘servoynavigation-menubar’.
I am attaching the SideNav example with my new base responsive form as well as screen shots showing what I mean compared to my solution that is currently using ‘servoynavigation-menubar’.
If you can show me how to get this component to work in almost the same way (i.e. observing full height of browser for tabs in next column & collapsing allowing a reflow) I will happily switch to it, but otherwise, maybe you can think about supporting ‘servoynavigation-menubar’ as a BootStrap (Extra) Component ??
Thanks
Rafi
[SideNav.zip](https://github.com/Servoy/servoy-extra-components/files/973923/SideNav.zip)

**Comment by paronne** [comment]
Hi Rafi, see below answer to the issue you listed

- the problem of the full height is not due to the sidenav component but to it's container. You have set the class bs-full-height to each div container but you missed to set bs-full-height to the form itself (which is the root container). Just add bs-full-height to the styleClass of the form and this issue is fixed.

- About resizing columns when the menu is collapsed, bootstrap columns have a fixed width (depending on screen size of course) which won't adapt to the width of it's content. When the menu is collapsed, still your first column will take 33% of the width. You cannot use bootstrap columns to separate the menu from the content of the page to achieve such behavior. You could use customDiv properly styled, but i the easier way to achieve it is to use a Servoy splitpanel, panel1 contains the menu, panel2 contains the content; when the menu is collapsed (there is an onOpenToggle event) you can change the location of the splitpanel divider.

- The CSS i have proposed in my previous answer can be combined (however it requires more adjustment) with the style of the menu when collapsed to show only the icons instead of disappearing. I can consider this as a feature request and investigate if can be built-in the sidenav menu without breaking the current behavior.

**Comment by servoyguru** [comment]
Hi
thanks for the reply.
I have made some of your suggested changes.
Maybe we can discuss @ ServoyWorld
Thanks
