### ISSUE TITLE
YouTube Video Embedded

### ISSUE THREAD

**Issue by jurraburusvy** [Servoy/servoy-extra-components#58]
Hi,

The YouTube embedded video with AutoPlay does not work on Chrome. It only works under Edge.
And, is there a wey to constantly play a video? I mean, to play again after the end?

Regards

**Comment by costescuandrei** [comment]
Some of these options might not work on some browsers / types of players that are used. We do give that argument (autoplay=1) to Youtube in all browsers - so probably Chrome/Youtube combination does not support that.
I remember trying out the "loop" arg. when the component was initially added but it didn't work then; even the docs say it doesn't always work - so that is why it wasn't added. I see now that a workaround with a playlist of 1 + loop might work in more cases. But I didn't try that yet.

https://developers.google.com/youtube/player_parameters

Still interested in trying to make loop work with the workaround?

**Comment by costescuandrei** [comment]
Let me know if you still need this. Closing...
