### ISSUE TITLE
ENHANCEMENT: Add faclassExpression property to the Font-awesome component

### ISSUE THREAD

**Issue by SteveHawes** [Servoy/servoy-extra-components#62]
Currently, it is not easy to change the icon that is displayed at runtime unless you use code.

Allowing a dataprovider as well as a text class will make the component much more versatile.

**Comment by meraedit** [comment]
We refactored a bit our components and added an imageStyleClass to the 
[Data  Label component from the Bootstrap Components package ](https://github.com/Servoy/bootstrapcomponents/wiki/Data-Label)
This will be available in the next release.
So my suggestion is to use the Data Label instead because that also supports a dataprovider.
